CREATE TABLE Usr (
    Name TEXT NOT NULL,
    Item TEXT NOT NULL,
    DoubleValue INTEGER NOT NULL,
    ID SERIAL PRIMARY KEY
);
CREATE TABLE Itm (
    Name TEXT NOT NULL,
    Value INTEGER NOT NULL,
    DoubleValue INTEGER NOT NULL,
    ID SERIAL PRIMARY KEY
);
