CREATE TABLE Usr (
    Name TEXT,
    Item INTEGER,
    ID SERIAL PRIMARY KEY
);
CREATE TABLE Itm (
    Name TEXT,
    Value INTEGER,
    ID SERIAL PRIMARY KEY
);
 ALTER TABLE Usr ADD FOREIGN KEY (Item) REFERENCES Itm(ID);
