CREATE TABLE Usr (
    Name TEXT NOT NULL,
    Item TEXT NOT NULL,
    Tr BOOLEAN NOT NULL,
    S TEXT NOT NULL,
    N INTEGER NOT NULL,
    W REAL NOT NULL,
    ID SERIAL PRIMARY KEY
);
CREATE TABLE Itm (
    Name TEXT NOT NULL,
    Value INTEGER NOT NULL,
    DoubleValue INTEGER NOT NULL,
    ID SERIAL PRIMARY KEY
);
